"""Init migration

Revision ID: c4ce6961e229
Revises: 
Create Date: 2022-06-25 21:43:51.637805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4ce6961e229'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('parentId', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=1200), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('OFFER', 'CATEGORY', name='shopunittype'), nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updateDate', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_date'), 'products', ['date'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_parentId'), 'products', ['parentId'], unique=False)
    op.create_index(op.f('ix_products_updateDate'), 'products', ['updateDate'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_updateDate'), table_name='products')
    op.drop_index(op.f('ix_products_parentId'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_date'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
